FROM universeking/reco_mme_new
MAINTAINER universeking rexlin2012001@gmail.com

COPY ./location_iot /LOCATION/location_iot
RUN sed -i 's/\/home\/oai-epc\/Downloads\/location_iot/\/LOCATION\/location_iot/g' /LOCATION/location_iot/CMakeCache.txt

WORKDIR /LOCATION/location_iot
RUN cmake . && make

WORKDIR /
RUN echo "#!/bin/bash" > mme.sh
RUN echo "/LOCATION/location_iot/location" >> mme.sh

#config network
RUN sed -i 's/MME_INTERFACE_NAME_FOR_S1_MME         = "ens39";/MME_INTERFACE_NAME_FOR_S1_MME         = "eth0";/g' /usr/local/etc/oai/mme.conf
RUN sed -i 's/MME_IPV4_ADDRESS_FOR_S1_MME           = "192.188.2.2\/24";/MME_IPV4_ADDRESS_FOR_S1_MME           = "192.188.2.6\/24";/g' /usr/local/etc/oai/mme.conf
RUN sed -i 's/MME_INTERFACE_NAME_FOR_S11_MME        = "ens37";/MME_INTERFACE_NAME_FOR_S11_MME        = "eth0";/g' /usr/local/etc/oai/mme.conf
RUN sed -i 's/MME_IPV4_ADDRESS_FOR_S11_MME          = "192.188.2.2\/24";/MME_IPV4_ADDRESS_FOR_S11_MME          = "192.188.2.6\/24";/g' /usr/local/etc/oai/mme.conf
RUN sed -i 's/SGW_IPV4_ADDRESS_FOR_S11="10.0.0.3\/8";/SGW_IPV4_ADDRESS_FOR_S11="192.188.2.5\/24";/g' /usr/local/etc/oai/mme.conf
RUN sed -i 's/ConnectPeer= "hss.openair4G.eur" { ConnectTo = "127.0.0.1";/ConnectPeer= "hss.openair4G.eur" { ConnectTo = "192.188.2.4";/g' /usr/local/etc/oai/freeDiameter/mme_fd.conf

#config mme
RUN sed -i 's/yang.openair4G.eur/mme3.openair4G.eur/g' /usr/local/etc/oai/freeDiameter/mme_fd.conf
RUN echo "mme3" > hostname && cp hostname /etc/hostname
RUN echo "127.0.1.1 mme3.openair4G.eur mme3" >> /etc/hosts && echo "127.0.0.1 hss.openair4G.eur hss" >> /etc/hosts
WORKDIR /
RUN echo "#!/bin/bash" > mme.sh
RUN echo "/RECO/SCRIPTS/check_mme_s6a_certificate /usr/local/etc/oai/freeDiameter/ mme3.openair4G.eur" >> mme.sh
RUN echo "/LOCATION/location_iot/location" >> mme.sh
RUN sed -i 's/ubuntu.openair4G.eur/mme3.openair4G.eur/g' /usr/local/etc/oai/freeDiameter/mme_fd.conf
